version: '3.7'
services:
  grader:
    container_name: grader
    build: .
    restart: on-failure
    labels:
      - com.host.description=autograder
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:5000"

# networks:
#   default:
#     name: bridge_service
#     external: true
